version: 2
updates:
  # 更新 npm 依赖
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5  # 减少PR数量
    reviewers:
      - "Jasmine661"
    assignees:
      - "Jasmine661"
    commit-message:
      prefix: "chore"
      include: "scope"
    # 只允许直接依赖更新，避免间接依赖冲突
    allow:
      - dependency-type: "direct"
    # 忽略的依赖更新
    ignore:
      # 忽略 FontAwesome 大版本更新，避免破坏性变更
      - dependency-name: "@fortawesome/*"
        update-types: ["version-update:semver-major"]
      # 忽略 Vite 大版本更新
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      # 忽略 jsdom 大版本更新
      - dependency-name: "jsdom"
        update-types: ["version-update:semver-major"]
      # 忽略 React 大版本更新
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # 忽略 TypeScript 大版本更新
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      # 忽略 Storybook 大版本更新
      - dependency-name: "@storybook/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "storybook"
        update-types: ["version-update:semver-major"]
    # 分组更新
    groups:
      # 测试相关依赖
      test-dependencies:
        patterns:
          - "@testing-library/*"
          - "@vitest/*"
          - "vitest"
          - "playwright"
          - "jsdom"
      # Storybook 相关依赖
      storybook-dependencies:
        patterns:
          - "@storybook/*"
          - "@chromatic-com/storybook"
          - "storybook"
      # ESLint 相关依赖
      eslint-dependencies:
        patterns:
          - "@eslint/*"
          - "eslint*"
          - "typescript-eslint"
          - "globals"
      # 类型定义依赖
      type-dependencies:
        patterns:
          - "@types/*"
      # 构建工具依赖
      build-dependencies:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "sass"
          - "terser"