# CI/CD 管道配置文件
# 这个文件定义了当代码推送到 GitHub 时自动执行的构建、测试和部署流程

# actions的名字
name: CI/CD Pipeline

# 触发条件：定义什么时候运行这个工作流
on:
  # 当代码推送到 main 或 develop 分支时触发
  push:
    branches: [ main, develop ]
  # 当有人创建或更新 Pull Request 到 main 分支时触发
  pull_request:
    branches: [ main ]
  # 当创建 GitHub Release 时触发
  release:
    types: [ published ]

# 定义要执行的任务
jobs:
  # 第一个任务：测试和代码检查
  test:
    name: Test & Lint
    runs-on: ubuntu-latest  # 在 Ubuntu 最新版本上运行
    
    # 矩阵策略：在多个 Node.js 版本上并行运行测试
    strategy:
      matrix:
        node-version: [18, 20]  # 测试 Node.js 18 和 20 版本
    
    # 执行步骤
    steps:
    # 步骤1：检出代码到运行器
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 步骤2：设置指定版本的 Node.js
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # 启用 npm 缓存以加速安装
        
    # 步骤3：安装 pnpm 包管理器
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    # 步骤4：安装项目依赖
    - name: Install dependencies
      run: pnpm install --frozen-lockfile  # 使用锁文件确保依赖版本一致
      
    # 步骤5：运行 ESLint 代码检查
    - name: Run linting
      run: pnpm run lint
      
    # 步骤6：运行单元测试
    - name: Run tests
      run: pnpm run test:nowatch
      
    # 步骤7：运行 Storybook 测试
    - name: Run Storybook tests
      run: pnpm run test:storybook

  # 第二个任务：构建和发布到 npm
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: test  # 依赖测试任务完成才能执行
    # 只在推送到 main 分支时执行（避免在 PR 时发布）
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    # 步骤1：检出代码
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 步骤2：设置 Node.js 并配置 npm 注册表
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'  # 指定 npm 官方注册表
        
    # 步骤3：安装 pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    # 步骤4：安装依赖
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    # 步骤5：构建组件库
    - name: Build package
      run: pnpm run build
      
    # 步骤6：发布到 npm
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # 使用存储的 npm 令牌
        
    # 步骤7：创建 GitHub Release（为代码创建版本标签，包含发布说明和变更日志
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 GitHub 令牌
      with:
        tag_name: v${{ github.ref_name }}  # 使用分支名作为标签
        release_name: Release v${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          - Updated component library
          - Bug fixes and improvements
          
          ## Installation
          
          ```bash
          npm install jasmine661-ui@${{ github.ref_name }}
          ```
        draft: false      # 不是草稿
        prerelease: false # 不是预发布版本

  # 第三个任务：构建 Storybook 并部署到 GitHub Pages
  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: test  # 依赖测试任务完成
    # 只在推送到 main 分支时执行
    if: github.ref == 'refs/heads/main'
    
    # 设置 GitHub Pages 所需的权限
    permissions:
      contents: read    # 读取仓库内容
      pages: write      # 写入 GitHub Pages
      id-token: write   # 写入身份令牌
      
    steps:
    # 步骤1：检出代码
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 步骤2：设置 Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    # 步骤3：安装 pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    # 步骤4：安装依赖
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    # 步骤5：构建 Storybook 静态文件
    - name: Build Storybook
      run: pnpm run build-storybook
      
    # 步骤6：配置 GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    # 步骤7：上传构建产物
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: storybook-static  # Storybook 构建输出目录
        
    # 步骤8：部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
